export const ORDER_CREATE_REQUEST: string = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS: string = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE: string = 'ORDER_CREATE_FAILURE'

export const ORDER_DETAILS_REQUEST: string = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS: string = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE: string = 'ORDER_DETAILS_FAILURE'

export const ORDER_PAY_REQUEST: string = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS: string = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE: string = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET: string = 'ORDER_PAY_RESET'

export const ORDER_LIST_SELF_REQUEST: string = 'ORDER_LIST_SELF_REQUEST'
export const ORDER_LIST_SELF_SUCCESS: string = 'ORDER_LIST_SELF_SUCCESS'
export const ORDER_LIST_SELF_FAILURE: string = 'ORDER_LIST_SELF_FAILURE'
export const ORDER_LIST_SELF_RESET: string = 'ORDER_LIST_SELF_RESET'
