export const ORDER_CREATE_REQUEST: string = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS: string = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE: string = 'ORDER_CREATE_FAILURE'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST: string = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS: string = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE: string = 'ORDER_DETAILS_FAILURE'

export const ORDER_PAY_REQUEST: string = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS: string = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE: string = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET: string = 'ORDER_PAY_RESET'

export const ORDER_DELIVER_REQUEST: string = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS: string = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAILURE: string = 'ORDER_DELIVER_FAILURE'
export const ORDER_DELIVER_RESET: string = 'ORDER_DELIVER_RESET'

export const ORDER_LIST_SELF_REQUEST: string = 'ORDER_LIST_SELF_REQUEST'
export const ORDER_LIST_SELF_SUCCESS: string = 'ORDER_LIST_SELF_SUCCESS'
export const ORDER_LIST_SELF_FAILURE: string = 'ORDER_LIST_SELF_FAILURE'
export const ORDER_LIST_SELF_RESET: string = 'ORDER_LIST_SELF_RESET'

export const ORDER_LIST_REQUEST: string = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS: string = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE: string = 'ORDER_LIST_FAILURE'
