export const ORDER_CREATE_REQUEST: string = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS: string = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE: string = 'ORDER_CREATE_FAILURE'
