export const PRODUCT_LIST_REQUEST: string = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS: string = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE: string = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_DETAIL_REQUEST: string = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS: string = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAILURE: string = 'PRODUCT_DETAIL_FAILURE'
