export const PRODUCT_LIST_REQUEST: string = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS: string = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE: string = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_DETAIL_REQUEST: string = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS: string = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAILURE: string = 'PRODUCT_DETAIL_FAILURE'

export const PRODUCT_DELETE_REQUEST: string = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS: string = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAILURE: string = 'PRODUCT_DELETE_FAILURE'

export const PRODUCT_CREATE_REQUEST: string = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS: string = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAILURE: string = 'PRODUCT_CREATE_FAILURE'
export const PRODUCT_CREATE_RESET: string = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST: string = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS: string = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAILURE: string = 'PRODUCT_UPDATE_FAILURE'
export const PRODUCT_UPDATE_RESET: string = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST: string = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS: string = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAILURE: string = 'PRODUCT_CREATE_REVIEW_FAILURE'
export const PRODUCT_CREATE_REVIEW_RESET: string = 'PRODUCT_CREATE_REVIEW_RESET'
