export const USER_LOGIN_REQUEST: string = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS: string = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE: string = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT: string = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST: string = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS: string = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE: string = 'USER_REGISTER_FAILURE'

export const USER_DETAILS_REQUEST: string = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS: string = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILURE: string = 'USER_DETAILS_FAILURE'

export const USER_UPDATE_PROFILE_REQUEST: string = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS: string = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILURE: string = 'USER_UPDATE_PROFILE_FAILURE'
export const USER_UPDATE_PROFILE_RESET: string = 'USER_UPDATE_PROFILE_RESET'
